% opposite(Verb,Opposite):
opposite(abandon,embrace).
opposite(abandon,adopt).
opposite(abandon,pursue).
opposite(abandon,renew).
opposite(abandon,continue).
opposite(abandon,accept).
opposite(abandon,defend).
opposite(abandon,favor).
opposite(abduct,slaughter).
opposite(abhor,tolerate).
opposite(abhor,embrace).
opposite(abolish,repeal).
opposite(abolish,enact).
opposite(abolish,impose).
opposite(abolish,ban).
opposite(abolish,reinstate).
opposite(abolish,legalize).
opposite(abolish,institute).
opposite(abrogate,revise).
opposite(abrogate,renegotiate).
opposite(abrogate,ratify).
opposite(abrogate,enforce).
opposite(absorb,produce).
opposite(absorb,generate).
opposite(absorb,withstand).
opposite(absorb,supply).
opposite(absorb,recoup).
opposite(absorb,secrete).
opposite(abut,adjoin).
opposite(accelerate,slow).
opposite(accelerate,hinder).
opposite(accelerate,curb).
opposite(accelerate,delay).
opposite(accept,reject).
opposite(accept,refuse).
opposite(accept,oppose).
opposite(accept,rescind).
opposite(accept,ignore).
opposite(accept,reiterate).
opposite(accept,rebuff).
opposite(accuse,blame).
opposite(accuse,urge).
opposite(accuse,praise).
opposite(acknowledge,downplay).
opposite(acknowledge,deny).
opposite(acknowledge,ignore).
opposite(acquire,lose).
opposite(acquire,divest).
opposite(acquit,convict).
opposite(acquit,sentence).
opposite(acquit,indict).
opposite(acquit,censure).
opposite(activate,deactivate).
opposite(add,drop).
opposite(address,ignore).
opposite(adjoin,abut).
opposite(adjoin,house).
opposite(adjourn,recess).
opposite(administer,withhold).
opposite(admire,hate).
opposite(admire,dislike).
opposite(admire,doubt).
opposite(admire,find).
opposite(admit,deny).
opposite(admonish,caution).
opposite(adopt,reject).
opposite(adore,hate).
opposite(adore,dislike).
opposite(adore,despise).
opposite(adore,pity).
opposite(adore,detest).
opposite(adore,marry).
opposite(advance,decline).
opposite(advocate,oppose).
opposite(advocate,denounce).
opposite(advocate,reject).
opposite(advocate,condemn).
opposite(advocate,criticize).
opposite(affect,reflect).
opposite(affect,plague).
opposite(affirm,overturn).
opposite(affirm,overrule).
opposite(affirm,reconsider).
opposite(affirm,reverse).
opposite(affirm,invalidate).
opposite(affirm,reject).
opposite(affirm,contradict).
opposite(afford,want).
opposite(air,premiere).
opposite(airlift,ferry).
opposite(alarm,dismay).
opposite(alert,caution).
opposite(alienate,energize).
opposite(allege,charge).
opposite(allege,document).
opposite(allege,cite).
opposite(alleviate,cause).
opposite(alleviate,deepen).
opposite(allow,prohibit).
opposite(allow,ban).
opposite(allow,forbid).
opposite(allow,bar).
opposite(allow,prevent).
opposite(allow,block).
opposite(allow,outlaw).
opposite(amaze,bore).
opposite(ambush,escort).
opposite(amend,annul).
opposite(amend,revoke).
opposite(amend,nullify).
opposite(amend,override).
opposite(anger,please).
opposite(annex,cede).
opposite(annihilate,vanquish).
opposite(annoy,interest).
opposite(annoy,bore).
opposite(annoy,terrify).
opposite(annoy,intrigue).
opposite(annul,amend).
opposite(annul,uphold).
opposite(annul,ratify).
opposite(annul,postpone).
opposite(annul,enforce).
opposite(annul,approve).
opposite(answer,rebuff).
opposite(answer,deflect).
opposite(answer,refuse).
opposite(answer,reject).
opposite(answer,dodge).
opposite(antagonize,appease).
opposite(antagonize,placate).
opposite(appeal,await).
opposite(appeal,enforce).
opposite(appease,antagonize).
opposite(appease,infuriate).
opposite(appease,persuade).
opposite(appease,inflame).
opposite(appease,sway).
opposite(append,delete).
opposite(applaud,criticize).
opposite(applaud,deride).
opposite(applaud,oppose).
opposite(applaud,denounce).
opposite(applaud,decry).
opposite(applaud,protest).
opposite(appoint,elect).
opposite(approve,reject).
opposite(approve,postpone).
opposite(approve,suspend).
opposite(approve,delay).
opposite(approve,oppose).
opposite(arbitrate,settle).
opposite(argue,concede).
opposite(argue,ignore).
opposite(arm,disarm).
opposite(arm,fight).
opposite(arrange,provide).
opposite(ask,say).
opposite(assail,ridicule).
opposite(assail,question).
opposite(assail,praise).
opposite(assassinate,murder).
opposite(assassinate,topple).
opposite(assert,reiterate).
opposite(assert,question).
opposite(assert,assume).
opposite(assume,inherit).
opposite(assume,assert).
opposite(assume,reiterate).
opposite(assure,thank).
opposite(attach,insert).
opposite(attack,overrun).
opposite(attend,host).
opposite(attend,boycott).
opposite(auction,liquidate).
opposite(auction,allocate).
opposite(authorise,restrict).
opposite(authorize,prohibit).
opposite(authorize,ban).
opposite(authorize,suspend).
opposite(authorize,forbid).
opposite(authorize,bar).
opposite(authorize,condemn).
opposite(authorize,reject).
opposite(average,drop).
opposite(await,appeal).
opposite(await,undergo).
opposite(award,withhold).
opposite(award,rescind).
opposite(back,oppose).
opposite(back,condemn).
opposite(bake,fry).
opposite(bake,saute).
opposite(bake,steam).
opposite(bake,mash).
opposite(bake,boil).
opposite(bake,refrigerate).
opposite(balance,boost).
opposite(ban,permit).
opposite(ban,legalize).
opposite(ban,authorize).
opposite(ban,exempt).
opposite(ban,allow).
opposite(ban,abolish).
opposite(bar,permit).
opposite(bar,authorize).
opposite(bar,allow).
opposite(bar,regulate).
opposite(bar,govern).
opposite(barricade,besiege).
opposite(base,ignore).
opposite(bash,poke).
opposite(bat,slug).
opposite(bat,miss).
opposite(beam,transmit).
opposite(beam,stream).
opposite(beat,trounce).
opposite(beat,blank).
opposite(become,need).
opposite(begin,continue).
opposite(begin,end).
opposite(begin,conclude).
opposite(begin,stop).
opposite(behead,free).
opposite(believe,understand).
opposite(believe,dispute).
opposite(believe,hate).
opposite(belittle,dispute).
opposite(belt,hammer).
opposite(benefit,harm).
opposite(benefit,hurt).
opposite(benefit,jeopardize).
opposite(berth,dock).
opposite(berth,moor).
opposite(besiege,barricade).
opposite(bite,trap).
opposite(blame,accuse).
opposite(blame,acknowledge).
opposite(blame,praise).
opposite(blanch,pickle).
opposite(blank,beat).
opposite(blink,shine).
opposite(block,approve).
opposite(block,permit).
opposite(blockade,picket).
opposite(blockade,guard).
opposite(blow,tear).
opposite(bludgeon,kill).
opposite(blue,white).
opposite(blunt,sharpen).
opposite(blur,reflect).
opposite(bobble,throw).
opposite(boil,fry).
opposite(boil,roast).
opposite(boil,eat).
opposite(boil,grill).
opposite(boil,steam).
opposite(boil,soak).
opposite(boil,bake).
opposite(bolster,undermine).
opposite(bolster,weaken).
opposite(bolster,undercut).
opposite(bolster,erode).
opposite(bolster,diminish).
opposite(bolt,quit).
opposite(boo,cheer).
opposite(boost,cut).
opposite(boost,weaken).
opposite(boost,depress).
opposite(boot,lace).
opposite(bore,excite).
opposite(bore,annoy).
opposite(bore,amaze).
opposite(bore,fascinate).
opposite(bore,entertain).
opposite(bore,intrigue).
opposite(borrow,lend).
opposite(borrow,buy).
opposite(borrow,donate).
opposite(borrow,deposit).
opposite(bottle,jar).
opposite(bottle,dry).
opposite(bottle,squeeze).
opposite(bounce,line).
opposite(bounce,miss).
opposite(boycott,attend).
opposite(boycott,contest).
opposite(boycott,participate).
opposite(braise,chop).
opposite(brandish,fire).
opposite(brandish,use).
opposite(breach,weaken).
opposite(bread,cake).
opposite(breastfeed,cry).
opposite(breed,graze).
opposite(bribe,coerce).
opposite(bribe,intimidate).
opposite(brighten,dim).
opposite(brine,marinate).
opposite(broadcast,programme).
opposite(broaden,limit).
opposite(broaden,restrict).
opposite(broaden,narrow).
opposite(broil,saute).
opposite(broker,renew).
opposite(bronze,silver).
opposite(browse,search).
opposite(brush,dismiss).
opposite(brush,ignore).
opposite(brush,sidestep).
opposite(bug,debug).
opposite(build,renovate).
opposite(build,buy).
opposite(build,purchase).
opposite(bundle,resell).
opposite(burn,erect).
opposite(burn,spray).
opposite(burn,douse).
opposite(burn,haul).
opposite(burst,collapse).
opposite(bury,miss).
opposite(bury,wash).
opposite(bury,destroy).
opposite(bury,burn).
opposite(bury,herd).
opposite(bury,scatter).
opposite(bury,leave).
opposite(bury,evacuate).
opposite(bus,flight).
opposite(butter,stick).
opposite(butter,pickle).
opposite(butter,oil).
opposite(buttress,refute).
opposite(buttress,undermine).
opposite(buy,build).
opposite(buy,donate).
opposite(buy,lease).
opposite(buy,borrow).
opposite(cake,bread).
opposite(call,write).
opposite(calm,quell).
opposite(cancel,reschedule).
opposite(cancel,suspend).
opposite(cancel,hold).
opposite(cancel,renew).
opposite(cancel,approve).
opposite(cancel,defer).
opposite(cancel,accept).
opposite(castigate,praise).
opposite(catch,miss).
opposite(cause,prevent).
opposite(cause,provoke).
opposite(cause,alleviate).
opposite(cause,cure).
opposite(caution,alert).
opposite(caution,admonish).
opposite(caution,worry).
opposite(caution,pressure).
opposite(cease,resume).
opposite(cease,continue).
opposite(cease,commence).
opposite(cease,restart).
opposite(cede,relinquish).
opposite(cede,annex).
opposite(cede,retain).
opposite(censure,acquit).
opposite(centralize,decentralize).
opposite(centralize,outsource).
opposite(certify,decertify).
opposite(certify,exempt).
opposite(certify,reinstate).
opposite(challenge,defend).
opposite(challenge,endorse).
opposite(challenge,support).
opposite(challenge,uphold).
opposite(challenge,accept).
opposite(change,abandon).
opposite(characterize,outline).
opposite(charge,allege).
opposite(charge,reimburse).
opposite(charge,suspect).
opposite(chart,outline).
opposite(chase,trail).
opposite(cheer,boo).
opposite(cheese,ham).
opposite(cherish,forget).
opposite(chide,praise).
opposite(chill,warm).
opposite(chill,weaken).
opposite(choke,paralyze).
opposite(choke,drown).
opposite(chop,grate).
opposite(chop,shred).
opposite(chop,flake).
opposite(chis_complement_of,slice).
opposite(circle,cross).
opposite(circumvent,defy).
opposite(circumvent,ease).
opposite(cite,dismiss).
opposite(claim,have).
opposite(claim,declare).
opposite(clap,pat).
opposite(clap,cry).
opposite(clarify,nullify).
opposite(clarify,contradict).
opposite(classify,declassify).
opposite(classify,exempt).
opposite(climb,fall).
opposite(climb,drop).
opposite(climb,edge).
opposite(climb,sink).
opposite(climb,fell).
opposite(climb,decrease).
opposite(clinch,win).
opposite(clinch,finish).
opposite(clinch,lose).
opposite(clock,finish).
opposite(clog,jam).
opposite(clone,mate).
opposite(coach,play).
opposite(coat,salt).
opposite(coddle,coerce).
opposite(coerce,bribe).
opposite(coerce,coddle).
opposite(coerce,arrest).
opposite(collapse,demolish).
opposite(collapse,burst).
opposite(collide,ram).
opposite(commence,suspend).
opposite(commence,cease).
opposite(commence,accelerate).
opposite(commend,criticize).
opposite(comment,insist).
opposite(communicate,comprehend).
opposite(commute,overturn).
opposite(commute,reverse).
opposite(complement,mirror).
opposite(compound,diminish).
opposite(comprehend,communicate).
opposite(compromise,safeguard).
opposite(compromise,reinforce).
opposite(conceal,disclose).
opposite(conceal,reveal).
opposite(conceal,acknowledge).
opposite(concede,contest).
opposite(concede,argue).
opposite(concede,relinquish).
opposite(concede,lose).
opposite(concede,claim).
opposite(concede,deny).
opposite(concede,ignore).
opposite(concede,cite).
opposite(concern,highlight).
opposite(conclude,begin).
opposite(condemn,support).
opposite(condemn,urge).
opposite(condemn,tolerate).
opposite(condemn,welcome).
opposite(condemn,authorize).
opposite(condemn,back).
opposite(condemn,hail).
opposite(condemn,justify).
opposite(condition,freeze).
opposite(confer,guarantee).
opposite(confess,deny).
opposite(confess,kill).
opposite(confirm,reject).
opposite(confirm,dispute).
opposite(confirm,deny).
opposite(confirm,refute).
opposite(confirm,contradict).
opposite(confirm,dismiss).
opposite(confirm,condemn).
opposite(confiscate,retrieve).
opposite(confront,ignore).
opposite(confront,fear).
opposite(confront,avoid).
opposite(confuse,ignore).
opposite(confuse,exaggerate).
opposite(congratulate,inform).
opposite(congratulate,warn).
opposite(congratulate,criticize).
opposite(connect,disconnect).
opposite(conserve,consume).
opposite(consider,oppose).
opposite(constitute,trigger).
opposite(constrain,hinder).
opposite(constrain,spur).
opposite(constrain,stimulate).
opposite(constrict,dilate).
opposite(consult,audit).
opposite(consume,export).
opposite(consume,conserve).
opposite(consume,hoard).
opposite(contain,leak).
opposite(contemplate,fear).
opposite(contend,allege).
opposite(contest,boycott).
opposite(contest,concede).
opposite(contest,accept).
opposite(continue,begin).
opposite(continue,end).
opposite(continue,halt).
opposite(continue,cease).
opposite(continue,start).
opposite(continue,initiate).
opposite(continue,stop).
opposite(continue,suspend).
opposite(contract,grow).
opposite(contradict,corroborate).
opposite(contradict,substantiate).
opposite(contradict,echo).
opposite(contradict,confirm).
opposite(contradict,clarify).
opposite(contradict,reinforce).
opposite(contradict,validate).
opposite(contradict,bolster).
opposite(contradict,reaffirm).
opposite(contradict,justify).
opposite(contradict,affirm).
opposite(contrast,echo).
opposite(contrast,repeat).
opposite(contravene,undermine).
opposite(convene,postpone).
opposite(convict,acquit).
opposite(convict,exonerate).
opposite(convict,suspect).
opposite(convict,murder).
opposite(convict,free).
opposite(convince,dissuade).
opposite(cool,warm).
opposite(cool,fuel).
opposite(correct,delete).
opposite(corroborate,contradict).
opposite(corroborate,rebut).
opposite(corroborate,disprove).
opposite(corroborate,dispute).
opposite(countenance,condone).
opposite(counter,reinforce).
opposite(counteract,avert).
opposite(court,shun).
opposite(crack,smack).
opposite(crash,fly).
opposite(crash,flight).
opposite(crave,prefer).
opposite(crave,eat).
opposite(crave,find).
opposite(credit,fault).
opposite(cremate,incinerate).
opposite(criminalize,legalize).
opposite(cripple,spur).
opposite(criticise,criticize).
opposite(criticise,commend).
opposite(criticize,praise).
opposite(criticize,endorse).
opposite(criticize,support).
opposite(criticize,applaud).
opposite(criticize,defend).
opposite(cross,patrol).
opposite(cross,circle).
opposite(crowd,line).
opposite(cruise,fly).
opposite(crush,slice).
opposite(cry,scream).
opposite(cry,breastfeed).
opposite(cry,clap).
opposite(cry,dye).
opposite(cry,wait).
opposite(cube,slice).
opposite(cube,grate).
opposite(cube,shred).
opposite(cube,mince).
opposite(cube,grind).
opposite(cube,mash).
opposite(curb,accelerate).
opposite(cure,cause).
opposite(curse,pity).
opposite(curtail,reduce).
opposite(curtail,increase).
opposite(curtail,hinder).
opposite(curtail,boost).
opposite(curtail,facilitate).
opposite(curtail,expand).
opposite(curtail,stimulate).
opposite(cut,boost).
opposite(cut,hike).
opposite(cycle,row).
opposite(damage,submerge).
opposite(damage,raze).
opposite(damn,darn).
opposite(damn,embarrass).
opposite(dampen,fuel).
opposite(dampen,spur).
opposite(dampen,heighten).
opposite(dampen,reflect).
opposite(dampen,boost).
opposite(dampen,stimulate).
opposite(dance,singe).
opposite(dare,hate).
opposite(darn,damn).
opposite(deactivate,activate).
opposite(debug,bug).
opposite(debis_complement_of,document).
opposite(decentralize,centralize).
opposite(decertify,certify).
opposite(decide,consider).
opposite(decimate,threaten).
opposite(declare,reiterate).
opposite(declare,renounce).
opposite(declassify,classify).
opposite(decline,rise).
opposite(decline,grow).
opposite(decode,sequence).
opposite(decode,embed).
opposite(decrease,increase).
opposite(decrease,exceed).
opposite(decrease,rise).
opposite(decrease,grow).
opposite(decrease,climb).
opposite(decree,legislate).
opposite(decry,applaud).
opposite(decry,endorse).
opposite(decry,resist).
opposite(decry,advocate).
opposite(deduct,refund).
opposite(deem,enforce).
opposite(deem,ignore).
opposite(deem,recommend).
opposite(deepen,ease).
opposite(deepen,alleviate).
opposite(deface,defile).
opposite(defend,criticize).
opposite(defend,challenge).
opposite(defend,denounce).
opposite(defend,oppose).
opposite(defend,reject).
opposite(defend,condemn).
opposite(defend,assail).
opposite(defend,attack).
opposite(defer,approve).
opposite(defer,authorize).
opposite(defer,accept).
opposite(defer,cancel).
opposite(defer,rescind).
opposite(defer,propose).
opposite(defer,refuse).
opposite(defile,deface).
opposite(deflect,tip).
opposite(deflect,sidestep).
opposite(deflect,answer).
opposite(defraud,sue).
opposite(defrost,thaw).
opposite(defuse,escalate).
opposite(defuse,detonate).
opposite(defuse,provoke).
opposite(defuse,inflame).
opposite(defy,obey).
opposite(defy,accept).
opposite(defy,circumvent).
opposite(defy,respect).
opposite(degrade,harm).
opposite(delay,expedite).
opposite(delay,approve).
opposite(delay,accelerate).
opposite(delay,hasten).
opposite(delete,encrypt).
opposite(delete,insert).
opposite(delete,append).
opposite(delete,rewrite).
opposite(delete,correct).
opposite(deliver,promise).
opposite(demand,reject).
opposite(demobilize,mobilize).
opposite(demolish,renovate).
opposite(demolish,refurbish).
opposite(demote,sack).
opposite(denigrate,compliment).
opposite(denounce,support).
opposite(denounce,advocate).
opposite(denounce,endorse).
opposite(denounce,urge).
opposite(denounce,praise).
opposite(deny,acknowledge).
opposite(deny,confirm).
opposite(deny,admit).
opposite(deny,grant).
opposite(deny,accept).
opposite(deny,disclose).
opposite(deny,renew).
opposite(deny,reiterate).
opposite(deny,withdraw).
opposite(depict,symbolize).
opposite(deplore,welcome).
opposite(deploy,redeploy).
opposite(deport,jail).
opposite(deport,prosecute).
opposite(deport,naturalize).
opposite(deport,execute).
opposite(deposit,reinvest).
opposite(deposit,borrow).
opposite(depress,boost).
opposite(depress,stimulate).
opposite(deprive,deter).
opposite(derail,hamper).
opposite(derail,weaken).
opposite(derail,fuel).
opposite(deride,applaud).
opposite(deride,embrace).
opposite(desert,occupy).
opposite(deserve,get).
opposite(deserve,have).
opposite(deserve,accept).
opposite(deserve,appreciate).
opposite(deserve,make).
opposite(deserve,feel).
opposite(desire,enjoy).
opposite(desire,regret).
opposite(desire,judge).
opposite(despise,love).
opposite(despise,adore).
opposite(despise,forgive).
opposite(despise,embrace).
opposite(destabilize,stabilize).
opposite(detail,summarize).
opposite(detain,massacre).
opposite(detect,found).
opposite(deter,embolden).
opposite(deter,encourage).
opposite(deter,prompt).
opposite(deter,escalate).
opposite(detest,adore).
opposite(detest,admire).
opposite(detest,love).
opposite(detonate,defuse).
opposite(dice,grate).
opposite(dice,shred).
opposite(dictate,respect).
opposite(dilate,constrict).
opposite(dilute,increase).
opposite(dilute,enhance).
opposite(dilute,affect).
opposite(dim,brighten).
opposite(dim,rekindle).
opposite(diminish,heighten).
opposite(diminish,bolster).
opposite(diminish,sap).
opposite(diminish,increase).
opposite(diminish,boost).
opposite(dip,slip).
opposite(dip,drop).
opposite(disable,reboot).
opposite(disallow,permit).
opposite(disappoint,please).
opposite(disappoint,excite).
opposite(disappoint,gratify).
opposite(disapprove,condone).
opposite(disapprove,endorse).
opposite(disapprove,table).
opposite(disarm,arm).
opposite(discard,stockpile).
opposite(discharge,recycle).
opposite(disclose,withhold).
opposite(disclose,conceal).
opposite(disclose,deny).
opposite(disconcert,excite).
opposite(disconnect,connect).
opposite(disconnect,reroute).
opposite(discontinue,cancel).
opposite(discontinue,redesign).
opposite(discount,downplay).
opposite(discount,ignore).
opposite(discount,attribute).
opposite(discourage,encourage).
opposite(discourage,spur).
opposite(discourage,stimulate).
opposite(discourage,permit).
opposite(discourage,entice).
opposite(discuss,postpone).
opposite(disgust,distract).
opposite(dishearten,hearten).
opposite(dislike,love).
opposite(dislike,prefer).
opposite(dislike,embrace).
opposite(dislike,adore).
opposite(dislike,admire).
opposite(dismantle,modernize).
opposite(dismantle,strengthen).
opposite(dismay,alarm).
opposite(dismiss,dispute).
opposite(dismiss,refute).
opposite(dismiss,brush).
opposite(dismiss,ignore).
opposite(dismiss,cite).
opposite(dismiss,quash).
opposite(dismiss,confirm).
opposite(dismiss,accept).
opposite(disobey,obey).
opposite(disparage,question).
opposite(dispatch,defeat).
opposite(dispatch,expel).
opposite(dispel,disprove).
opposite(dispel,quell).
opposite(disperse,subdue).
opposite(disprove,substantiate).
opposite(disprove,corroborate).
opposite(disprove,dispel).
opposite(disprove,validate).
opposite(disprove,prove).
opposite(disprove,confirm).
opposite(disprove,vindicate).
opposite(disprove,bolster).
opposite(disprove,verify).
opposite(dispute,dismiss).
opposite(dispute,confirm).
opposite(dispute,substantiate).
opposite(dispute,corroborate).
opposite(dispute,echo).
opposite(dispute,acknowledge).
opposite(disqualify,punish).
opposite(disregard,heed).
opposite(disregard,respect).
opposite(disregard,obey).
opposite(disregard,enforce).
opposite(disregard,override).
opposite(disregard,uphold).
opposite(disregard,misinterpret).
opposite(disregard,accept).
opposite(disrespect,trust).
opposite(disrespect,respect).
opposite(dissuade,persuade).
opposite(dissuade,reassure).
opposite(dissuade,convince).
opposite(dissuade,placate).
opposite(dissuade,influence).
opposite(distort,ignore).
opposite(distract,motivate).
opposite(distress,gratify).
opposite(distrust,trust).
opposite(ditch,crash).
opposite(divert,pump).
opposite(divest,own).
opposite(divest,acquire).
opposite(divest,operate).
opposite(divest,transfer).
opposite(divest,privatize).
opposite(do,say).
opposite(do,try).
opposite(do,know).
opposite(do,love).
opposite(do,feel).
opposite(do,talk).
opposite(dock,moor).
opposite(dock,berth).
opposite(dock,station).
opposite(document,allege).
opposite(dodge,answer).
opposite(dodge,ignore).
opposite(dodge,throw).
opposite(dole,withhold).
opposite(dole,lavish).
opposite(dominate,miss).
opposite(don,unzip).
opposite(don,grab).
opposite(don,wave).
opposite(don,pull).
opposite(donate,sell).
opposite(donate,buy).
opposite(donate,purchase).
opposite(donate,borrow).
opposite(doom,complicate).
opposite(doubt,infer).
opposite(douse,burn).
opposite(downgrade,upgrade).
opposite(downgrade,cut).
opposite(downgrade,rate).
opposite(download,scan).
opposite(download,stream).
opposite(downplay,acknowledge).
opposite(downplay,discount).
opposite(downplay,overstate).
opposite(downplay,explain).
opposite(downplay,emphasize).
opposite(downsize,expand).
opposite(downsize,upgrade).
opposite(drain,siphon).
opposite(drain,pump).
opposite(drain,freeze).
opposite(dress,pant).
opposite(drill,knock).
opposite(drink,sip).
opposite(drink,swig).
opposite(drink,inhale).
opposite(drop,rise).
opposite(drop,dip).
opposite(drop,climb).
opposite(drop,add).
opposite(dry,snip).
opposite(dry,freeze).
opposite(duck,ignore).
opposite(dull,whet).
opposite(dump,spill).
opposite(dump,wash).
opposite(dump,spray).
opposite(dump,burn).
opposite(dupe,fool).
opposite(dye,cry).
opposite(dye,drown).
opposite(dye,grieve).
opposite(earmark,approve).
opposite(earmark,provide).
opposite(ease,worsen).
opposite(ease,tighten).
opposite(ease,exacerbate).
opposite(eat,crave).
opposite(eat,boil).
opposite(eat,weigh).
opposite(echo,contradict).
opposite(echo,dispute).
opposite(edge,climb).
opposite(edge,rise).
opposite(elaborate,refute).
opposite(elect,appoint).
opposite(elevate,bring).
opposite(embarrass,trust).
opposite(embed,decode).
opposite(embed,insert).
opposite(embed,bundle).
opposite(embezzle,misappropriate).
opposite(embody,inspire).
opposite(embolden,deter).
opposite(embolden,weaken).
opposite(embrace,abandon).
opposite(embrace,ignore).
opposite(embrace,oppose).
opposite(embrace,reject).
opposite(embrace,deride).
opposite(embrace,ridicule).
opposite(emit,transmit).
opposite(emphasise,neglect).
opposite(emphasize,praise).
opposite(empower,prohibit).
opposite(empower,oppress).
opposite(enable,hinder).
opposite(enable,discourage).
opposite(enact,repeal).
opposite(enact,abolish).
opposite(enact,propose).
opposite(encircle,overrun).
opposite(encounter,found).
opposite(encourage,discourage).
opposite(encourage,restrict).
opposite(encourage,forbid).
opposite(encrypt,delete).
opposite(end,continue).
opposite(end,begin).
opposite(end,start).
opposite(end,escalate).
opposite(endanger,harm).
opposite(endanger,undermine).
opposite(endanger,hinder).
opposite(endanger,erode).
opposite(endorse,oppose).
opposite(endorse,reject).
opposite(endorse,criticize).
opposite(endorse,veto).
opposite(endorse,denounce).
opposite(endorse,challenge).
opposite(endure,ignore).
opposite(endure,remember).
opposite(energize,alienate).
opposite(energize,hurt).
opposite(enforce,violate).
opposite(enforce,revoke).
opposite(enforce,repeal).
opposite(engage,please).
opposite(engage,alienate).
opposite(engender,undermine).
opposite(enjoin,void).
opposite(enjoin,forbid).
opposite(enjoy,have).
opposite(enlarge,restrict).
opposite(enlarge,curtail).
opposite(enlarge,reduce).
opposite(ensure,undermine).
opposite(entail,mean).
opposite(entail,preclude).
opposite(entail,ensure).
opposite(entail,constitute).
opposite(enter,exit).
opposite(entertain,bore).
opposite(entice,discourage).
opposite(envision,fear).
opposite(envision,intend).
opposite(envy,pity).
opposite(erect,burn).
opposite(erode,boost).
opposite(erode,bolster).
opposite(erode,increase).
opposite(erode,endanger).
opposite(escalate,defuse).
opposite(escalate,end).
opposite(escape,suffer).
opposite(eschew,embrace).
opposite(escort,ambush).
opposite(espouse,profess).
opposite(espouse,endorse).
opposite(espouse,support).
opposite(estimate,forecast).
opposite(evade,violate).
opposite(evade,seek).
opposite(evade,face).
opposite(evoke,provoke).
opposite(evoke,illustrate).
opposite(exacerbate,ease).
opposite(exacerbate,provoke).
opposite(exacerbate,lessen).
opposite(exacerbate,reduce).
opposite(exacerbate,diminish).
opposite(exacerbate,stem).
opposite(exacerbate,prompt).
opposite(exaggerate,overstate).
opposite(exaggerate,underestimate).
opposite(exaggerate,understate).
opposite(exaggerate,ignore).
opposite(exaggerate,underplay).
opposite(exaggerate,trivialize).
opposite(exceed,decrease).
opposite(exceed,fall).
opposite(excite,disappoint).
opposite(excite,bore).
opposite(excite,disconcert).
opposite(exclude,include).
opposite(exclude,require).
opposite(excoriate,praise).
opposite(execute,deport).
opposite(execute,kill).
opposite(execute,release).
opposite(exempt,prohibit).
opposite(exempt,levy).
opposite(exempt,ban).
opposite(exempt,forbid).
opposite(exempt,authorize).
opposite(exempt,impose).
opposite(exempt,limit).
opposite(exempt,require).
opposite(exempt,subsidize).
opposite(exert,resist).
opposite(exit,enter).
opposite(exonerate,implicate).
opposite(exonerate,convict).
opposite(exonerate,indict).
opposite(exonerate,incriminate).
opposite(exonerate,impeach).
opposite(exonerate,prosecute).
opposite(exonerate,punish).
opposite(exonerate,censure).
opposite(expand,limit).
opposite(expand,restrict).
opposite(expand,reduce).
opposite(expect,see).
opposite(expect,get).
opposite(expedite,delay).
opposite(expedite,postpone).
opposite(expel,massacre).
opposite(expel,disarm).
opposite(expel,slaughter).
opposite(explain,downplay).
opposite(explain,ignore).
opposite(exploit,ignore).
opposite(export,invest).
opposite(export,consume).
opposite(expose,cause).
opposite(express,underscore).
opposite(exterminate,deport).
opposite(extradite,prosecute).
opposite(extradite,free).
opposite(fabricate,obtain).
opposite(facilitate,hinder).
opposite(facilitate,restrict).
opposite(fail,flis_complement_of).
opposite(fail,pass).
opposite(fail,undergo).
opposite(fall,rise).
opposite(fall,jump).
opposite(fall,climb).
opposite(fall,firm).
opposite(fan,walk).
opposite(farm,herd).
opposite(fascinate,bore).
opposite(fascinate,frighten).
opposite(fascinate,unsettle).
opposite(fault,blame).
opposite(fault,endorse).
opposite(favor,oppose).
opposite(favor,propose).
opposite(favor,reject).
opposite(favor,want).
opposite(favor,criticize).
opposite(favor,resist).
opposite(fax,phone).
opposite(fear,contemplate).
opposite(feature,star).
opposite(feature,resemble).
opposite(feature,sport).
opposite(feel,get).
opposite(feel,notice).
opposite(feel,know).
opposite(feel,enjoy).
opposite(feel,do).
opposite(fell,rise).
opposite(fell,jump).
opposite(fell,gain).
opposite(fell,climb).
opposite(fence,swim).
opposite(ferry,airlift).
opposite(ferry,fly).
opposite(fight,tolerate).
opposite(fight,suffer).
opposite(film,premiere).
opposite(find,found).
opposite(find,get).
opposite(find,like).
opposite(finish,start).
opposite(finish,rank).
opposite(finish,clock).
opposite(finish,score).
opposite(finish,shoot).
opposite(finish,qualify).
opposite(finish,clinch).
opposite(finish,bat).
opposite(fire,lob).
opposite(fire,brandish).
opposite(fire,hurl).
opposite(fire,slam).
opposite(firm,fall).
opposite(flake,shred).
opposite(flake,grate).
opposite(flake,chop).
opposite(flake,slice).
opposite(flee,invade).
opposite(fleece,knit).
opposite(flight,crash).
opposite(flight,bus).
opposite(flip,knock).
opposite(float,devalue).
opposite(flood,affect).
opposite(flour,sugar).
opposite(flout,fulfill).
opposite(flis_complement_of,fail).
opposite(fly,crash).
opposite(fly,ferry).
opposite(foil,sabre).
opposite(fool,dupe).
opposite(forbid,permit).
opposite(forbid,authorize).
opposite(forbid,limit).
opposite(forbid,allow).
opposite(forbid,exempt).
opposite(forbid,legalize).
opposite(forbid,encourage).
opposite(forbid,require).
opposite(forbid,sanction).
opposite(forecast,estimate).
opposite(foreclose,limit).
opposite(forego,accept).
opposite(foreshadow,reflect).
opposite(foreshadow,mirror).
opposite(forestall,alleviate).
opposite(forestall,accelerate).
opposite(forget,remember).
opposite(forget,hate).
opposite(forget,cherish).
opposite(forget,recall).
opposite(forgive,punish).
opposite(forgive,judge).
opposite(forgive,despise).
opposite(forgive,reschedule).
opposite(forgo,accept).
opposite(fortify,evacuate).
opposite(foster,undermine).
opposite(foul,bounce).
opposite(found,find).
opposite(found,uncover).
opposite(found,examine).
opposite(found,detect).
opposite(found,use).
opposite(found,recover).
opposite(found,unearth).
opposite(found,retrieve).
opposite(found,seize).
opposite(found,leave).
opposite(found,throw).
opposite(found,check).
opposite(free,kidnap).
opposite(free,extradite).
opposite(free,wound).
opposite(free,behead).
opposite(free,convict).
opposite(free,apprehend).
opposite(freeze,restart).
opposite(freeze,dry).
opposite(freeze,postpone).
opposite(freeze,cut).
opposite(freeze,peel).
opposite(frighten,galvanize).
opposite(frighten,fascinate).
opposite(frustrate,allow).
opposite(fry,saute).
opposite(fry,bake).
opposite(fry,peel).
opposite(fry,boil).
opposite(fry,steam).
opposite(fuel,spark).
opposite(fuel,trigger).
opposite(fuel,dampen).
opposite(fulfill,violate).
opposite(fulfill,flout).
opposite(fumble,muff).
opposite(fumble,return).
opposite(fumble,catch).
opposite(fumble,score).
opposite(fumble,scramble).
opposite(fumble,grab).
opposite(funnel,siphon).
opposite(fuse,replicate).
opposite(gain,lose).
opposite(gain,regain).
opposite(gain,fell).
opposite(gallop,jog).
opposite(gather,lack).
opposite(get,miss).
opposite(get,deserve).
opposite(get,score).
opposite(get,pitch).
opposite(get,find).
opposite(get,feel).
opposite(glamorize,trivialize).
opposite(glorify,trivialize).
opposite(govern,bar).
opposite(grab,miss).
opposite(grab,score).
opposite(grab,wield).
opposite(graft,transplant).
opposite(grant,revoke).
opposite(grant,deny).
opposite(grant,withhold).
opposite(grant,reject).
opposite(grant,refuse).
opposite(grant,loan).
opposite(grant,withdraw).
opposite(grant,renew).
opposite(grate,chop).
opposite(grate,dice).
opposite(grate,slice).
opposite(grate,grind).
opposite(grate,cube).
opposite(grate,sliver).
opposite(grate,flake).
opposite(gratify,disappoint).
opposite(gratify,distress).
opposite(graze,breed).
opposite(graze,pierce).
opposite(greet,tell).
opposite(greet,assure).
opposite(greet,warn).
opposite(grill,saute).
opposite(grill,boil).
opposite(grind,grate).
opposite(grind,cube).
opposite(grind,slice).
opposite(grow,shrink).
opposite(grow,decline).
opposite(grow,decrease).
opposite(guard,raid).
opposite(guard,attack).
opposite(guard,blockade).
opposite(guard,inspect).
opposite(guess,laugh).
opposite(guess,memorize).
opposite(guess,hate).
opposite(gut,repeal).
opposite(guzzle,sip).
opposite(hail,criticize).
opposite(hail,condemn).
opposite(halt,resume).
opposite(halt,continue).
opposite(halve,shred).
opposite(ham,cheese).
opposite(hammer,belt).
opposite(hammer,beat).
opposite(hamper,derail).
opposite(hamper,spur).
opposite(hang,throw).
opposite(harbor,voice).
opposite(harbour,shelter).
opposite(harden,soften).
opposite(harm,endanger).
opposite(harm,threaten).
opposite(harm,benefit).
opposite(hasten,delay).
opposite(hasten,hinder).
opposite(hasten,slow).
opposite(hasten,halt).
opposite(hasten,impede).
opposite(hasten,prevent).
opposite(hasten,avert).
opposite(hasten,forestall).
opposite(hatch,nest).
opposite(hate,love).
opposite(hate,adore).
opposite(hate,know).
opposite(hate,want).
opposite(hate,forget).
opposite(hate,embrace).
opposite(hate,see).
opposite(hate,believe).
opposite(hate,admire).
opposite(haul,burn).
opposite(have,lack).
opposite(have,enjoy).
opposite(heal,stitch).
opposite(hear,ignore).
opposite(hear,know).
opposite(hear,dismiss).
opposite(hear,yell).
opposite(hearten,dishearten).
opposite(hedge,leverage).
opposite(heed,disregard).
opposite(heed,reject).
opposite(heighten,diminish).
opposite(heighten,dampen).
opposite(heighten,lessen).
opposite(heighten,weaken).
opposite(help,hurt).
opposite(help,discourage).
opposite(help,harm).
opposite(herd,kill).
opposite(hide,stash).
opposite(hide,disclose).
opposite(hike,cut).
opposite(hinder,facilitate).
opposite(hinder,constrain).
opposite(hinder,spur).
opposite(hinder,accelerate).
opposite(hinder,stimulate).
opposite(hire,reassign).
opposite(hit,miss).
opposite(hit,throw).
opposite(hit,walk).
opposite(hit,nail).
opposite(hoard,resell).
opposite(hoe,plough).
opposite(hoist,burn).
opposite(hold,cancel).
opposite(hold,postpone).
opposite(hold,seek).
opposite(hole,putt).
opposite(honey,salt).
opposite(hook,trip).
opposite(host,attend).
opposite(house,adjoin).
opposite(hover,whirl).
opposite(hug,pat).
opposite(hunt,herd).
opposite(hurl,lob).
opposite(hurl,fire).
opposite(hurl,use).
opposite(hurt,boost).
opposite(hurt,benefit).
opposite(hurt,help).
opposite(ignite,rekindle).
opposite(ignore,dismiss).
opposite(ignore,accept).
opposite(ignore,acknowledge).
opposite(ignore,address).
opposite(ignore,resist).
opposite(ignore,obey).
opposite(ignore,embrace).
opposite(ignore,explain).
opposite(ignore,enforce).
opposite(illuminate,obscure).
opposite(illustrate,evoke).
opposite(imagine,relive).
opposite(imitate,like).
opposite(impact,jeopardize).
opposite(impeach,exonerate).
opposite(impede,accelerate).
opposite(impede,restrict).
opposite(impede,hasten).
opposite(implant,transplant).
opposite(implant,repair).
opposite(implicate,exonerate).
opposite(imply,signify).
opposite(imply,mask).
opposite(imply,prompt).
opposite(import,produce).
opposite(import,manufacture).
opposite(import,smuggle).
opposite(impose,relax).
opposite(impose,abolish).
opposite(impose,lift).
opposite(impose,rescind).
opposite(impose,waive).
opposite(impose,suspend).
opposite(impose,revoke).
opposite(impose,reinstate).
opposite(imprison,massacre).
opposite(imprison,expel).
opposite(improvise,rehearse).
opposite(improvise,memorize).
opposite(inactivate,mutate).
opposite(incarcerate,hospitalize).
opposite(incinerate,cremate).
opposite(incite,suppress).
opposite(increase,reduce).
opposite(increase,decrease).
opposite(increase,limit).
opposite(incriminate,exonerate).
opposite(indict,acquit).
opposite(indict,exonerate).
opposite(induce,relieve).
opposite(induce,suppress).
opposite(induce,prevent).
opposite(induce,alleviate).
opposite(infer,doubt).
opposite(infer,presume).
opposite(inflame,defuse).
opposite(inflame,appease).
opposite(influence,mirror).
opposite(inform,criticize).
opposite(inform,congratulate).
opposite(infringe,violate).
opposite(infuriate,appease).
opposite(infuse,inject).
opposite(ingest,inhale).
opposite(ingest,sniff).
opposite(inhale,smell).
opposite(inhale,ingest).
opposite(inhale,drink).
opposite(inhale,eat).
opposite(inhale,consume).
opposite(inherit,assume).
opposite(inhibit,stimulate).
opposite(inhibit,suppress).
opposite(initiate,continue).
opposite(inject,pump).
opposite(inject,infuse).
opposite(inject,insert).
opposite(insert,delete).
opposite(insert,attach).
opposite(insert,embed).
opposite(insert,inject).
opposite(insist,oppose).
opposite(insist,confirm).
opposite(insist,comment).
opposite(inspect,raid).
opposite(inspire,mirror).
opposite(inspire,embody).
opposite(instigate,intensify).
opposite(institute,abolish).
opposite(institute,revise).
opposite(instruct,urge).
opposite(insult,compliment).
opposite(intend,envision).
opposite(intend,consider).
opposite(interest,annoy).
opposite(interrupt,delay).
opposite(interrupt,repeat).
opposite(intimidate,bribe).
opposite(intrigue,annoy).
opposite(intrigue,bore).
opposite(introduce,reintroduce).
opposite(inundate,wash).
opposite(invade,flee).
opposite(invalidate,uphold).
opposite(invalidate,validate).
opposite(invalidate,affirm).
opposite(invalidate,amend).
opposite(invest,export).
opposite(invest,repay).
opposite(investigate,reexamine).
opposite(invite,accuse).
opposite(invoke,waive).
opposite(invoke,mention).
opposite(invoke,repudiate).
opposite(invoke,propose).
opposite(irrigate,replant).
opposite(issue,reject).
opposite(jail,deport).
opposite(jam,clog).
opposite(jar,bottle).
opposite(jeopardize,impact).
opposite(jog,gallop).
opposite(join,rejoin).
opposite(join,leave).
opposite(journey,voyage).
opposite(judge,underestimate).
opposite(judge,prejudge).
opposite(judge,forgive).
opposite(jump,fall).
opposite(jump,slip).
opposite(jump,fell).
opposite(jump,retreat).
opposite(jis_complement_of,amend).
opposite(justify,condemn).
opposite(justify,denounce).
opposite(justify,contradict).
opposite(justify,authorize).
opposite(keep,lose).
opposite(keep,stop).
opposite(keep,pull).
opposite(keep,turn).
opposite(keep,regain).
opposite(keep,remove).
opposite(kick,miss).
opposite(kick,nail).
opposite(kick,throw).
opposite(kidnap,free).
opposite(kill,herd).
opposite(knit,fleece).
opposite(knock,beat).
opposite(knock,rip).
opposite(knock,pull).
opposite(knock,throw).
opposite(knock,grab).
opposite(knock,get).
opposite(knock,drill).
opposite(knock,miss).
opposite(knock,defeat).
opposite(know,remember).
opposite(know,want).
opposite(know,hate).
opposite(know,do).
opposite(know,hear).
opposite(know,feel).
opposite(know,say).
opposite(label,ignore).
opposite(lace,boot).
opposite(lack,have).
opposite(lack,lose).
opposite(lag,outperform).
opposite(lag,exceed).
opposite(lag,decrease).
opposite(lambast,praise).
opposite(lambast,laud).
opposite(lament,applaud).
opposite(lap,second).
opposite(lash,hit).
opposite(laud,lambast).
opposite(laugh,scream).
opposite(laugh,yell).
opposite(laugh,sigh).
opposite(laugh,guess).
opposite(laugh,sympathize).
opposite(laugh,feel).
opposite(lavish,dole).
opposite(lead,trail).
opposite(lead,sweep).
opposite(leak,contain).
opposite(leak,disclose).
opposite(lease,own).
opposite(lease,purchase).
opposite(lease,buy).
opposite(lease,sell).
opposite(lease,resell).
opposite(lease,build).
opposite(leave,join).
opposite(leave,keep).
opposite(leave,found).
opposite(leave,destroy).
opposite(legalize,outlaw).
opposite(legalize,ban).
opposite(legalize,prohibit).
opposite(legalize,restrict).
opposite(legalize,criminalize).
opposite(legalize,forbid).
opposite(legalize,abolish).
opposite(legalize,bar).
opposite(legalize,allow).
opposite(legislate,impose).
opposite(legislate,promulgate).
opposite(legitimize,undermine).
opposite(legitimize,outlaw).
opposite(legitimize,reform).
opposite(lend,loan).
opposite(lend,borrow).
opposite(lend,offer).
opposite(lend,grant).
opposite(lend,donate).
opposite(lengthen,shorten).
opposite(lessen,heighten).
opposite(lessen,increase).
opposite(lessen,exacerbate).
opposite(lessen,worsen).
opposite(let,keep).
opposite(let,hate).
opposite(let,know).
opposite(let,watch).
opposite(let,believe).
opposite(level,devastate).
opposite(leverage,hedge).
opposite(levy,exempt).
opposite(levy,suspend).
opposite(levy,propose).
opposite(libel,slander).
opposite(liberalize,restrict).
opposite(liberalize,tighten).
opposite(liberate,recapture).
opposite(lift,impose).
opposite(lift,slide).
opposite(lighten,lessen).
opposite(like,see).
opposite(like,find).
opposite(like,get).
opposite(like,prefer).
opposite(like,keep).
opposite(liken,call).
opposite(liken,consider).
opposite(limit,increase).
opposite(limit,expand).
opposite(limit,broaden).
opposite(limit,forbid).
opposite(limit,maximize).
opposite(line,crowd).
opposite(line,bounce).
opposite(liquidate,recapitalize).
opposite(liquidate,restructure).
opposite(liquidate,refinance).
opposite(liquidate,merge).
opposite(liquidate,auction).
opposite(list,recommend).
opposite(live,spend).
opposite(loan,lend).
opposite(loan,grant).
opposite(loathe,adore).
opposite(lob,hurl).
opposite(lob,fire).
opposite(localize,standardize).
opposite(lock,unlock).
opposite(lodge,reject).
opposite(loosen,tighten).
opposite(loosen,repeal).
opposite(loosen,stiffen).
opposite(loosen,strengthen).
opposite(loosen,sever).
opposite(loot,shell).
opposite(lose,gain).
opposite(lose,regain).
opposite(lose,win).
opposite(lose,retain).
opposite(lose,need).
opposite(lose,score).
opposite(lose,lack).
opposite(love,hate).
opposite(love,see).
opposite(love,have).
opposite(love,get).
opposite(love,despise).
opposite(love,do).
opposite(lower,raise).
opposite(magnify,lessen).
opposite(mail,deliver).
opposite(make,accept).
opposite(manipulate,disregard).
opposite(manufacture,import).
opposite(manufacture,purchase).
opposite(manufacture,smuggle).
opposite(marinate,brine).
opposite(marry,wed).
opposite(marry,adore).
opposite(mash,slice).
opposite(mash,cube).
opposite(mash,bake).
opposite(mask,mirror).
opposite(mask,imply).
opposite(massacre,detain).
opposite(massacre,expel).
opposite(mate,clone).
opposite(maximize,limit).
opposite(maximize,minimize).
opposite(maximize,curtail).
opposite(mean,entail).
opposite(meet,warn).
opposite(melt,salt).
opposite(memorize,improvise).
opposite(memorize,guess).
opposite(merge,buy).
opposite(merge,sell).
opposite(merge,liquidate).
opposite(mess,screw).
opposite(mimic,simulate).
opposite(mince,sliver).
opposite(mince,cube).
opposite(mince,powder).
opposite(mince,taste).
opposite(minimise,offset).
opposite(minimize,overstate).
opposite(minimize,maximize).
opposite(mirror,influence).
opposite(mirror,mask).
opposite(misappropriate,embezzle).
opposite(misappropriate,solicit).
opposite(misconstrue,misunderstand).
opposite(misinterpret,misread).
opposite(misinterpret,disregard).
opposite(misinterpret,ignore).
opposite(misinterpret,cite).
opposite(misread,misinterpret).
opposite(misread,misunderstand).
opposite(misread,read).
opposite(misread,ignore).
opposite(misrepresent,ignore).
opposite(misrepresent,misinterpret).
opposite(misrepresent,misunderstand).
opposite(miss,hit).
opposite(miss,score).
opposite(miss,nail).
opposite(miss,get).
opposite(miss,shoot).
opposite(miss,kick).
opposite(miss,swish).
opposite(miss,grab).
opposite(miss,catch).
opposite(miss,throw).
opposite(misspell,omit).
opposite(misstate,omit).
opposite(mist,twinkle).
opposite(mistrust,trust).
opposite(misunderstand,misconstrue).
opposite(misunderstand,ignore).
opposite(misunderstand,misread).
opposite(misunderstand,misrepresent).
opposite(misunderstand,disrespect).
opposite(mobilize,demobilize).
opposite(modernize,dismantle).
opposite(modify,enact).
opposite(moor,dock).
opposite(moor,berth).
opposite(motivate,distract).
opposite(motivate,discourage).
opposite(motivate,deter).
opposite(motivate,hurt).
opposite(mount,repel).
opposite(mow,spray).
opposite(muff,fumble).
opposite(mulch,sand).
opposite(mull,reject).
opposite(multiply,mitigate).
opposite(murder,assassinate).
opposite(murmur,scream).
opposite(mutate,inactivate).
opposite(mutter,yell).
opposite(nail,miss).
opposite(nail,hit).
opposite(nail,kick).
opposite(narrow,widen).
opposite(narrow,broaden).
opposite(narrow,expand).
opposite(nationalize,privatize).
opposite(nationalize,redistribute).
opposite(naturalize,deport).
opposite(need,lose).
opposite(need,become).
opposite(need,possess).
opposite(need,keep).
opposite(negate,underscore).
opposite(neglect,emphasise).
opposite(neglect,embrace).
opposite(neglect,exaggerate).
opposite(neighbour,neighbor).
opposite(nest,hatch).
opposite(neutralize,dismantle).
opposite(neutralize,detonate).
opposite(notch,score).
opposite(note,say).
opposite(notice,spot).
opposite(notice,sense).
opposite(notice,feel).
opposite(notice,ignore).
opposite(nullify,amend).
opposite(nullify,uphold).
opposite(nullify,override).
opposite(nullify,clarify).
opposite(nullify,enforce).
opposite(nullify,affirm).
opposite(obey,disobey).
opposite(obey,defy).
opposite(obey,disregard).
opposite(obey,ignore).
opposite(obey,transgress).
opposite(obey,violate).
opposite(object,endorse).
opposite(obscure,reflect).
opposite(obscure,underscore).
opposite(obscure,illuminate).
opposite(obstruct,pervert).
opposite(occupy,vacate).
opposite(occupy,destroy).
opposite(offend,harm).
opposite(offset,recoup).
opposite(oil,butter).
opposite(oil,salt).
opposite(omit,misspell).
opposite(omit,misstate).
opposite(omit,outline).
opposite(omit,explain).
opposite(omit,relate).
opposite(oppose,support).
opposite(oppose,advocate).
opposite(oppose,favor).
opposite(oppose,endorse).
opposite(oppose,back).
opposite(oppose,propose).
opposite(oppose,seek).
opposite(oppose,consider).
opposite(oppose,approve).
opposite(oppose,accept).
opposite(oppress,empower).
opposite(oust,elect).
opposite(outlast,overcome).
opposite(outlaw,legalize).
opposite(outlaw,permit).
opposite(outlaw,curb).
opposite(outlaw,sanction).
opposite(outperform,lag).
opposite(outsource,centralize).
opposite(overcome,outlast).
opposite(overemphasize,underestimate).
opposite(overestimate,underestimate).
opposite(overestimate,overstate).
opposite(overestimate,understate).
opposite(overestimate,expect).
opposite(overhaul,privatize).
opposite(overpay,underpay).
opposite(overpay,owe).
opposite(override,nullify).
opposite(override,amend).
opposite(override,disregard).
opposite(override,ignore).
opposite(override,approve).
opposite(override,ratify).
opposite(override,reject).
opposite(overrule,uphold).
opposite(overrule,affirm).
opposite(overrule,ignore).
opposite(overrun,attack).
opposite(overrun,encircle).
opposite(overshadow,diminish).
opposite(overstate,understate).
opposite(overstate,exaggerate).
opposite(overstate,overestimate).
opposite(overstate,underestimate).
opposite(overstate,downplay).
opposite(overstate,minimize).
opposite(overstate,ignore).
opposite(overturn,uphold).
opposite(overturn,affirm).
opposite(overturn,enforce).
opposite(overturn,block).
opposite(overvalue,undervalue).
opposite(overwrite,uninstall).
opposite(owe,receive).
opposite(own,lease).
opposite(own,rent).
opposite(own,divest).
opposite(paint,found).
opposite(pair,feature).
opposite(pant,skirt).
opposite(pant,dress).
opposite(par,putt).
opposite(park,swerve).
opposite(parole,deport).
opposite(participate,boycott).
opposite(pass,fail).
opposite(pass,rush).
opposite(pat,hug).
opposite(pat,clap).
opposite(pat,slap).
opposite(pat,tone).
opposite(patrol,cross).
opposite(patrol,attack).
opposite(pay,receive).
opposite(peddle,use).
opposite(peel,fry).
opposite(peel,squeeze).
opposite(peg,boost).
opposite(penalize,reward).
opposite(perceive,tolerate).
opposite(perceive,ignore).
opposite(perform,singe).
opposite(permit,prohibit).
opposite(permit,forbid).
opposite(permit,bar).
opposite(permit,ban).
opposite(permit,outlaw).
opposite(permit,prevent).
opposite(permit,preclude).
opposite(permit,block).
opposite(perpetuate,subvert).
opposite(persuade,appease).
opposite(persuade,placate).
opposite(persuade,dissuade).
opposite(pervert,obstruct).
opposite(phone,fax).
opposite(photograph,scan).
opposite(photograph,found).
opposite(picket,blockade).
opposite(pickle,blanch).
opposite(pickle,butter).
opposite(piece,slice).
opposite(pitch,walk).
opposite(pitch,retire).
opposite(pitch,get).
opposite(placate,antagonize).
opposite(placate,persuade).
opposite(placate,dissuade).
opposite(plague,affect).
opposite(plan,postpone).
opposite(play,coach).
opposite(play,get).
opposite(play,rout).
opposite(please,anger).
opposite(please,disappoint).
opposite(plough,hoe).
opposite(poach,fry).
opposite(poke,bash).
opposite(poke,shake).
opposite(police,arm).
opposite(pollute,endanger).
opposite(pool,diversify).
opposite(possess,need).
opposite(postpone,approve).
opposite(postpone,discuss).
opposite(postpone,expedite).
opposite(postpone,plan).
opposite(postpone,welcome).
opposite(pour,pump).
opposite(pour,spray).
opposite(powder,mince).
opposite(powder,chop).
opposite(practise,inculcate).
opposite(praise,criticize).
opposite(praise,urge).
opposite(praise,emphasize).
opposite(praise,accuse).
opposite(praise,denounce).
opposite(praise,reiterate).
opposite(praise,outline).
opposite(praise,assail).
opposite(pray,clutch).
opposite(precipitate,trigger).
opposite(precipitate,worsen).
opposite(preclude,prohibit).
opposite(preclude,permit).
opposite(preclude,require).
opposite(preclude,authorize).
opposite(preclude,facilitate).
opposite(preclude,encourage).
opposite(preclude,allow).
opposite(prefer,crave).
opposite(prefer,like).
opposite(prefer,dislike).
opposite(prefer,try).
opposite(prefer,shun).
opposite(prejudge,judge).
opposite(prejudice,undermine).
opposite(prejudice,preempt).
opposite(premiere,air).
opposite(premiere,film).
opposite(prepay,refinance).
opposite(pressure,caution).
opposite(pressure,sack).
opposite(pressure,discourage).
opposite(presume,infer).
opposite(prevent,cause).
opposite(prevent,permit).
opposite(print,serialize).
opposite(privatize,nationalize).
opposite(privatize,overhaul).
opposite(privatize,upgrade).
opposite(prod,punish).
opposite(produce,import).
opposite(profess,espouse).
opposite(programme,broadcast).
opposite(prohibit,permit).
opposite(prohibit,authorize).
opposite(prohibit,exempt).
opposite(prohibit,legalize).
opposite(prohibit,preclude).
opposite(prohibit,require).
opposite(prohibit,allow).
opposite(prolong,resolve).
opposite(prolong,provoke).
opposite(prolong,resume).
opposite(prolong,terminate).
opposite(prolong,hasten).
opposite(prolong,hamper).
opposite(prolong,cause).
opposite(promise,oppose).
opposite(prompt,exacerbate).
opposite(promulgate,legislate).
opposite(propel,hurt).
opposite(propose,oppose).
opposite(propose,urge).
opposite(propose,recommend).
opposite(propose,favor).
opposite(propose,enact).
opposite(prosecute,extradite).
opposite(prosecute,deport).
opposite(prosecute,exonerate).
opposite(protect,destroy).
opposite(protest,reject).
opposite(protest,applaud).
opposite(protest,accept).
opposite(prove,disprove).
opposite(provide,earmark).
opposite(provoke,cause).
opposite(provoke,defuse).
opposite(provoke,exacerbate).
opposite(publish,reissue).
opposite(pull,keep).
opposite(pull,push).
opposite(pull,wear).
opposite(pull,knock).
opposite(pump,pour).
opposite(pump,inject).
opposite(pump,drain).
opposite(pump,divert).
opposite(punch,grab).
opposite(punch,hug).
opposite(punch,swing).
opposite(punish,reward).
opposite(punish,forgive).
opposite(purchase,sell).
opposite(purchase,manufacture).
opposite(purchase,lease).
opposite(purchase,donate).
opposite(purchase,build).
opposite(pursue,reject).
opposite(pursue,abandon).
opposite(push,pull).
opposite(putt,hole).
opposite(putt,par).
opposite(qualify,finish).
opposite(quash,dismiss).
opposite(quash,uphold).
opposite(quell,calm).
opposite(quell,intensify).
opposite(quell,dispel).
opposite(question,assail).
opposite(quit,resign).
opposite(quit,bolt).
opposite(quit,rejoin).
opposite(raid,guard).
opposite(raid,inspect).
opposite(raise,lower).
opposite(rally,dip).
opposite(rally,slide).
opposite(rally,fall).
opposite(rally,plunge).
opposite(rally,slip).
opposite(rally,drop).
opposite(ram,collide).
opposite(rank,finish).
opposite(rate,downgrade).
opposite(ratify,reject).
opposite(ratify,sign).
opposite(ratify,revise).
opposite(ratify,annul).
opposite(ratify,repeal).
opposite(ratify,revoke).
opposite(ratify,abrogate).
opposite(ratify,override).
opposite(rationalize,rectify).
opposite(rattle,hurt).
opposite(raze,damage).
opposite(reactivate,restart).
opposite(read,scribble).
opposite(read,misread).
opposite(ready,mount).
opposite(reaffirm,reconsider).
opposite(reassert,undermine).
opposite(reassign,hire).
opposite(reassure,thank).
opposite(reauthorize,repeal).
opposite(rebuff,accept).
opposite(rebuff,consider).
opposite(rebuild,renovate).
opposite(rebuke,praise).
opposite(rebut,corroborate).
opposite(rebut,substantiate).
opposite(rebut,undercut).
opposite(rebut,confirm).
opposite(recall,forget).
opposite(recapitalize,liquidate).
opposite(recapture,liberate).
opposite(receive,pay).
opposite(receive,refuse).
opposite(recess,adjourn).
opposite(recommend,propose).
opposite(recommend,endorse).
opposite(recommend,authorize).
opposite(recommend,reject).
opposite(reconfirm,reconsider).
opposite(reconsider,reexamine).
opposite(reconsider,reaffirm).
opposite(reconsider,uphold).
opposite(reconsider,affirm).
opposite(recount,acknowledge).
opposite(recoup,refund).
opposite(recoup,offset).
opposite(recover,found).
opposite(recover,drop).
opposite(recreate,replicate).
opposite(rectify,rationalize).
opposite(recycle,discharge).
opposite(recycle,contaminate).
opposite(redefine,preserve).
opposite(redefine,create).
opposite(redeploy,deploy).
opposite(redesign,introduce).
opposite(redesign,discontinue).
opposite(redistribute,nationalize).
opposite(reduce,increase).
opposite(reduce,curtail).
opposite(reduce,expand).
opposite(reestablish,revive).
opposite(reexamine,reconsider).
opposite(reexamine,investigate).
opposite(refer,dismiss).
opposite(refer,arbitrate).
opposite(refer,reject).
opposite(refinance,repay).
opposite(refinance,prepay).
opposite(reflect,affect).
opposite(reflect,dampen).
opposite(refocus,reinforce).
opposite(refrigerate,reheat).
opposite(refrigerate,simmer).
opposite(refrigerate,butter).
opposite(refrigerate,bake).
opposite(refund,deduct).
opposite(refund,recoup).
opposite(refund,collect).
opposite(refurbish,demolish).
opposite(refuse,accept).
opposite(refuse,request).
opposite(refuse,receive).
opposite(refuse,rescind).
opposite(refuse,withdraw).
opposite(refuse,grant).
opposite(refuse,withhold).
opposite(refuse,revoke).
opposite(refuse,renew).
opposite(refuse,ignore).
opposite(refuse,defer).
opposite(refuse,negotiate).
opposite(refute,dismiss).
opposite(refute,substantiate).
opposite(refute,confirm).
opposite(refute,buttress).
opposite(refute,repeat).
opposite(refute,clarify).
opposite(regain,lose).
opposite(regain,gain).
opposite(regard,fear).
opposite(regard,criticize).
opposite(regard,denounce).
opposite(rehearse,improvise).
opposite(reheat,refrigerate).
opposite(reimburse,subsidize).
opposite(reinforce,undermine).
opposite(reinforce,contradict).
opposite(reinstate,uphold).
opposite(reinstate,revoke).
opposite(reinstate,impose).
opposite(reinstate,abolish).
opposite(reinstate,repeal).
opposite(reinstate,rescind).
opposite(reinstate,reject).
opposite(reinstate,grant).
opposite(reinstate,enact).
opposite(reintroduce,introduce).
opposite(reintroduce,repeal).
opposite(reinvest,deposit).
opposite(reissue,publish).
opposite(reject,accept).
opposite(reject,approve).
opposite(reject,endorse).
opposite(reject,support).
opposite(reject,uphold).
opposite(reject,submit).
opposite(reject,withdraw).
opposite(rejoin,join).
opposite(rejoin,quit).
opposite(rekindle,spark).
opposite(rekindle,ignite).
opposite(rekindle,dim).
opposite(relate,omit).
opposite(relaunch,launch).
opposite(relax,tighten).
opposite(relax,impose).
opposite(relax,strengthen).
opposite(release,withhold).
opposite(release,detain).
opposite(relieve,cause).
opposite(relieve,lessen).
opposite(relieve,induce).
opposite(relinquish,cede).
opposite(relinquish,retain).
opposite(relinquish,seek).
opposite(relinquish,maintain).
opposite(relinquish,abandon).
opposite(relinquish,concede).
opposite(relive,imagine).
opposite(relive,feel).
opposite(remain,have).
opposite(remain,say).
opposite(remain,turn).
opposite(remand,sentence).
opposite(remedy,resolve).
opposite(remember,forget).
opposite(remember,know).
opposite(remember,endure).
opposite(remember,like).
opposite(remind,thank).
opposite(remind,congratulate).
opposite(remove,repair).
opposite(remove,keep).
opposite(renegotiate,terminate).
opposite(renegotiate,abrogate).
opposite(renegotiate,scrap).
opposite(renew,revoke).
opposite(renew,withdraw).
opposite(renew,suspend).
opposite(renew,deny).
opposite(renounce,reaffirm).
opposite(renounce,declare).
opposite(renounce,revoke).
opposite(renounce,advocate).
opposite(renounce,accept).
opposite(renovate,build).
opposite(renovate,rebuild).
opposite(renovate,demolish).
opposite(rent,own).
opposite(rent,purchase).
opposite(rent,sell).
opposite(reopen,shut).
opposite(reopen,establish).
opposite(repair,remove).
opposite(repair,transplant).
opposite(repay,refinance).
opposite(repay,invest).
opposite(repeal,enact).
opposite(repeal,abolish).
opposite(repeal,approve).
opposite(repeal,enforce).
opposite(repeal,reauthorize).
opposite(repeat,refute).
opposite(repel,mount).
opposite(replace,keep).
opposite(replace,resign).
opposite(replace,repair).
opposite(replant,irrigate).
opposite(replant,transplant).
opposite(replenish,absorb).
opposite(replicate,recreate).
opposite(replicate,fuse).
opposite(replicate,translate).
opposite(reposition,diversify).
opposite(reprimand,prosecute).
opposite(reproduce,synthesize).
opposite(repudiate,endorse).
opposite(repudiate,back).
opposite(repudiate,embrace).
opposite(request,refuse).
opposite(require,prohibit).
opposite(require,forbid).
opposite(require,exempt).
opposite(reroute,disconnect).
opposite(reschedule,cancel).
opposite(reschedule,scrap).
opposite(rescind,impose).
opposite(rescind,approve).
opposite(rescind,reject).
opposite(rescind,accept).
opposite(rescind,reverse).
opposite(rescind,enforce).
opposite(rescind,refuse).
opposite(rescind,reinstate).
opposite(rescue,kill).
opposite(rescue,arrest).
opposite(resell,lease).
opposite(resell,bundle).
opposite(resell,hoard).
opposite(resemble,feature).
opposite(resemble,contain).
opposite(resent,welcome).
opposite(resent,accept).
opposite(reshuffle,sack).
opposite(resign,sign).
opposite(resign,lose).
opposite(resign,quit).
opposite(resist,ignore).
opposite(resist,accept).
opposite(resist,demand).
opposite(resist,support).
opposite(resist,decry).
opposite(resist,favor).
opposite(resolve,remedy).
opposite(respect,disregard).
opposite(restart,reactivate).
opposite(restart,initiate).
opposite(restart,freeze).
opposite(restart,postpone).
opposite(restart,delay).
opposite(restore,undermine).
opposite(restrain,dampen).
opposite(restrict,facilitate).
opposite(restrict,legalize).
opposite(restrict,expand).
opposite(restructure,liquidate).
opposite(resume,halt).
opposite(resume,cease).
opposite(retain,relinquish).
opposite(retain,lose).
opposite(retain,cede).
opposite(retard,stimulate).
opposite(retard,affect).
opposite(retire,walk).
opposite(retire,pitch).
opposite(retreat,jump).
opposite(retrieve,confiscate).
opposite(retrieve,found).
opposite(retrofit,demolish).
opposite(return,fumble).
opposite(revalue,devalue).
opposite(reveal,conceal).
opposite(reverse,uphold).
opposite(reverse,affirm).
opposite(reverse,rescind).
opposite(reverse,reaffirm).
opposite(revile,pity).
opposite(revise,abrogate).
opposite(revive,reestablish).
opposite(revoke,grant).
opposite(revoke,suspend).
opposite(revoke,reinstate).
opposite(revoke,approve).
opposite(revoke,amend).
opposite(revoke,enforce).
opposite(revoke,renew).
opposite(revoke,impose).
opposite(revoke,uphold).
opposite(revoke,reject).
opposite(reward,punish).
opposite(reward,penalize).
opposite(reward,discourage).
opposite(rewrite,repeal).
opposite(rewrite,delete).
opposite(rewrite,scrap).
opposite(ride,pull).
opposite(ridicule,assail).
opposite(ridicule,applaud).
opposite(ridicule,endorse).
opposite(ridicule,embrace).
opposite(rip,knock).
opposite(ripen,rot).
opposite(rise,fall).
opposite(rise,tumble).
opposite(rise,drop).
opposite(rise,decline).
opposite(rise,fell).
opposite(rise,decrease).
opposite(rise,edge).
opposite(roast,saute).
opposite(roast,boil).
opposite(rob,detain).
opposite(roll,haul).
opposite(rot,ripen).
opposite(rout,play).
opposite(row,cycle).
opposite(rush,pass).
opposite(sabotage,stall).
opposite(sabre,foil).
opposite(sack,demote).
opposite(sack,pressure).
opposite(sack,reshuffle).
opposite(saddle,train).
opposite(safeguard,compromise).
opposite(sag,shrink).
opposite(sail,tow).
opposite(salt,honey).
opposite(salt,sugar).
opposite(salt,melt).
opposite(salt,oil).
opposite(salt,coat).
opposite(sanction,outlaw).
opposite(sanction,prohibit).
opposite(sanction,forbid).
opposite(sanction,condemn).
opposite(sanction,restrict).
opposite(sanction,postpone).
opposite(sand,mulch).
opposite(sap,diminish).
opposite(satisfy,stimulate).
opposite(saute,fry).
opposite(saute,broil).
opposite(saute,roast).
opposite(saute,grill).
opposite(saute,bake).
opposite(save,squander).
opposite(say,tell).
opposite(say,ask).
opposite(say,note).
opposite(say,do).
opposite(say,begin).
opposite(scan,download).
opposite(scatter,kill).
opposite(scatter,spray).
opposite(scatter,bury).
opposite(scoop,shovel).
opposite(scorch,destroy).
opposite(score,miss).
opposite(score,notch).
opposite(score,get).
opposite(score,finish).
opposite(score,lose).
opposite(score,grab).
opposite(scorn,accept).
opposite(scramble,fumble).
opposite(scrap,propose).
opposite(scrap,adopt).
opposite(scrap,approve).
opposite(scrap,enforce).
opposite(scrape,excavate).
opposite(scrawl,type).
opposite(scream,cry).
opposite(scream,laugh).
opposite(scream,murmur).
opposite(screw,mess).
opposite(scribble,read).
opposite(search,browse).
opposite(second,lap).
opposite(secrete,absorb).
opposite(see,expect).
opposite(see,like).
opposite(see,love).
opposite(seek,oppose).
opposite(segregate,prohibit).
opposite(seize,surrender).
opposite(sell,purchase).
opposite(sell,donate).
opposite(sense,notice).
opposite(sentence,acquit).
opposite(sentence,remand).
opposite(separate,shield).
opposite(sequence,decode).
opposite(serialize,print).
opposite(settle,arbitrate).
opposite(settle,avert).
opposite(settle,pursue).
opposite(settle,reject).
opposite(settle,deny).
opposite(settle,withdraw).
opposite(sever,strengthen).
opposite(sever,maintain).
opposite(sever,loosen).
opposite(shake,poke).
opposite(shame,pity).
opposite(sharpen,blunt).
opposite(sharpen,soften).
opposite(sharpen,lessen).
opposite(shell,loot).
opposite(shelter,evacuate).
opposite(shelter,harbour).
opposite(shelve,reject).
opposite(shelve,postpone).
opposite(shelve,propose).
opposite(shelve,defer).
opposite(shield,separate).
opposite(shift,reduce).
opposite(shine,blink).
opposite(ship,smuggle).
opposite(ship,stockpile).
opposite(shoot,miss).
opposite(shoot,finish).
opposite(shoot,stab).
opposite(shoot,get).
opposite(shorten,lengthen).
opposite(shout,shriek).
opposite(shove,throw).
opposite(shove,smash).
opposite(shovel,scoop).
opposite(shred,chop).
opposite(shred,dice).
opposite(shred,slice).
opposite(shred,flake).
opposite(shred,cube).
opposite(shred,halve).
opposite(shriek,shout).
opposite(shrink,grow).
opposite(shrink,swell).
opposite(shrink,widen).
opposite(shrink,expand).
opposite(shun,embrace).
opposite(shun,prefer).
opposite(shun,seek).
opposite(shun,court).
opposite(shut,reopen).
opposite(sidestep,ignore).
opposite(sidestep,resolve).
opposite(sidestep,repeat).
opposite(sidestep,brush).
opposite(sidestep,deflect).
opposite(sigh,laugh).
opposite(sign,resign).
opposite(sign,ratify).
opposite(sign,veto).
opposite(sign,reject).
opposite(signify,imply).
opposite(silence,please).
opposite(silence,provoke).
opposite(silver,bronze).
opposite(simmer,refrigerate).
opposite(simulate,mimic).
opposite(singe,perform).
opposite(singe,dance).
opposite(singe,record).
opposite(sink,slide).
opposite(sink,climb).
opposite(sink,rise).
opposite(sip,drink).
opposite(sip,guzzle).
opposite(siphon,funnel).
opposite(siphon,drain).
opposite(sit,stand).
opposite(sit,say).
opposite(sit,hang).
opposite(skip,take).
opposite(skirt,pant).
opposite(slam,whip).
opposite(slam,throw).
opposite(slander,libel).
opposite(slap,stroke).
opposite(slap,pat).
opposite(slaughter,abduct).
opposite(slaughter,expel).
opposite(slice,grate).
opposite(slice,cube).
opposite(slice,shred).
opposite(slice,sliver).
opposite(slice,flake).
opposite(slice,mash).
opposite(slice,grind).
opposite(slide,sink).
opposite(slide,rally).
opposite(slip,dip).
opposite(slip,jump).
opposite(sliver,mince).
opposite(sliver,grate).
opposite(sliver,slice).
opposite(slow,accelerate).
opposite(slow,spur).
opposite(slow,stimulate).
opposite(slow,hasten).
opposite(slow,boost).
opposite(slug,hit).
opposite(slug,bat).
opposite(smash,throw).
opposite(smell,inhale).
opposite(smell,clean).
opposite(smell,hate).
opposite(smuggle,ship).
opposite(smuggle,import).
opposite(smuggle,manufacture).
opposite(snatch,steal).
opposite(sniff,ingest).
opposite(snip,dry).
opposite(soak,boil).
opposite(soften,harden).
opposite(soften,toughen).
opposite(soften,sharpen).
opposite(soften,outline).
opposite(soften,reject).
opposite(solicit,misappropriate).
opposite(solicit,collect).
opposite(solve,worsen).
opposite(soothe,quell).
opposite(spare,punish).
opposite(spare,kill).
opposite(spark,fuel).
opposite(spark,rekindle).
opposite(spew,spray).
opposite(spill,dump).
opposite(split,sweep).
opposite(spoil,hurt).
opposite(sport,feature).
opposite(spot,notice).
opposite(sprain,twist).
opposite(sprain,tear).
opposite(spray,burn).
opposite(spray,pour).
opposite(spray,dump).
opposite(spray,remove).
opposite(spur,dampen).
opposite(spur,hinder).
opposite(spur,hamper).
opposite(spur,slow).
opposite(spur,discourage).
opposite(spurn,accept).
opposite(spurn,embrace).
opposite(squander,lose).
opposite(squander,save).
opposite(squeeze,peel).
opposite(squeeze,bottle).
opposite(stab,shoot).
opposite(stabilize,destabilize).
opposite(stabilize,weaken).
opposite(stall,sabotage).
opposite(stall,revive).
opposite(stall,intensify).
opposite(stand,sit).
opposite(star,feature).
opposite(start,finish).
opposite(start,end).
opposite(start,continue).
opposite(starve,strangle).
opposite(stash,hide).
opposite(state,suggest).
opposite(station,wound).
opposite(station,arm).
opposite(steal,snatch).
opposite(steam,fry).
opposite(steam,bake).
opposite(steam,boil).
opposite(stem,spur).
opposite(stew,roast).
opposite(stick,butter).
opposite(stick,cube).
opposite(stiffen,weaken).
opposite(stiffen,loosen).
opposite(stiffen,relax).
opposite(stiffen,modify).
opposite(stifle,spur).
opposite(stimulate,inhibit).
opposite(stimulate,hinder).
opposite(stimulate,slow).
opposite(stimulate,dampen).
opposite(stimulate,curtail).
opposite(stipulate,clarify).
opposite(stitch,heal).
opposite(stockpile,ship).
opposite(stone,assault).
opposite(stop,continue).
opposite(stop,begin).
opposite(stop,keep).
opposite(stop,intensify).
opposite(strain,pull).
opposite(strand,walk).
opposite(strangle,starve).
opposite(stream,download).
opposite(stream,beam).
opposite(strengthen,weaken).
opposite(stress,urge).
opposite(stroke,slap).
opposite(stunt,spur).
opposite(stymie,stymy).
opposite(stymy,stymie).
opposite(subdue,disperse).
opposite(subjugate,liberate).
opposite(submerge,damage).
opposite(submit,reject).
opposite(submit,withdraw).
opposite(subsidize,reimburse).
opposite(subsidize,exempt).
opposite(subsidize,restrict).
opposite(subsidize,tax).
opposite(substantiate,disprove).
opposite(substantiate,rebut).
opposite(substantiate,contradict).
opposite(substantiate,refute).
opposite(substantiate,dispute).
opposite(subvert,perpetuate).
opposite(subvert,assert).
opposite(sue,defraud).
opposite(suffer,survive).
opposite(suffer,escape).
opposite(suffer,fight).
opposite(sugar,salt).
opposite(sugar,flour).
opposite(suggest,propose).
opposite(suggest,acknowledge).
opposite(sully,taint).
opposite(summarize,detail).
opposite(summarize,dispute).
opposite(supervise,suspend).
opposite(support,oppose).
opposite(support,reject).
opposite(support,criticize).
opposite(support,denounce).
opposite(support,condemn).
opposite(support,veto).
opposite(suppress,stimulate).
opposite(suppress,inhibit).
opposite(suppress,trigger).
opposite(suppress,incite).
opposite(suppress,tolerate).
opposite(surmount,circumvent).
opposite(surprise,beat).
opposite(surrender,seize).
opposite(surrender,take).
opposite(survive,suffer).
opposite(suspect,convict).
opposite(suspect,charge).
opposite(suspend,cancel).
opposite(suspend,revoke).
opposite(suspend,approve).
opposite(suspend,authorize).
opposite(suspend,impose).
opposite(suspend,renew).
opposite(suspend,continue).
opposite(sustain,have).
opposite(swamp,destroy).
opposite(swat,miss).
opposite(swat,grab).
opposite(sway,appease).
opposite(sweep,lead).
opposite(swell,shrink).
opposite(swell,decrease).
opposite(swerve,park).
opposite(swig,drink).
opposite(swing,swinge).
opposite(swing,punch).
opposite(swinge,swing).
opposite(switch,keep).
opposite(symbolize,depict).
opposite(synthesize,reproduce).
opposite(taint,sully).
opposite(talk,do).
opposite(tally,miss).
opposite(tap,tape).
opposite(tap,divert).
opposite(tape,tap).
opposite(tar,ridicule).
opposite(taste,mince).
opposite(tax,subsidize).
opposite(tear,sprain).
opposite(tear,blow).
opposite(tell,say).
opposite(tell,thank).
opposite(tell,warn).
opposite(tend,eat).
opposite(tend,bury).
opposite(terminate,renegotiate).
opposite(terminate,suspend).
opposite(terminate,renew).
opposite(terminate,void).
opposite(terminate,finalize).
opposite(terminate,resume).
opposite(terminate,extend).
opposite(terminate,prolong).
opposite(terrify,annoy).
opposite(terrify,inspire).
opposite(thank,tell).
opposite(thank,assure).
opposite(thank,reassure).
opposite(thank,remind).
opposite(thank,criticize).
opposite(thaw,defrost).
opposite(threaten,harm).
opposite(throw,hit).
opposite(throw,walk).
opposite(throw,toss).
opposite(throw,miss).
opposite(throw,wave).
opposite(throw,smash).
opposite(thwart,halt).
opposite(tie,trail).
opposite(tighten,relax).
opposite(tighten,loosen).
opposite(tighten,ease).
opposite(tighten,liberalize).
opposite(tighten,repeal).
opposite(tip,deflect).
opposite(tire,wheel).
opposite(tolerate,condemn).
opposite(tolerate,abhor).
opposite(tolerate,fight).
opposite(tolerate,oppose).
opposite(tolerate,suppress).
opposite(tone,pat).
opposite(topple,assassinate).
opposite(topple,support).
opposite(torch,vandalize).
opposite(torch,damage).
opposite(torpedo,delay).
opposite(toss,throw).
opposite(toughen,soften).
opposite(tow,sink).
opposite(tow,sail).
opposite(tow,escort).
opposite(tow,fly).
opposite(trail,lead).
opposite(trail,tie).
opposite(trail,face).
opposite(train,saddle).
opposite(transgress,obey).
opposite(translate,replicate).
opposite(transmit,beam).
opposite(transmit,emit).
opposite(transplant,implant).
opposite(transplant,graft).
opposite(transplant,replant).
opposite(transplant,repair).
opposite(transplant,inject).
opposite(trap,bite).
opposite(trap,free).
opposite(trick,pity).
opposite(trigger,fuel).
opposite(trigger,precipitate).
opposite(trim,boost).
opposite(trip,hook).
opposite(trivialize,glorify).
opposite(trivialize,exaggerate).
opposite(trounce,beat).
opposite(trounce,face).
opposite(trump,outweigh).
opposite(trust,distrust).
opposite(trust,disrespect).
opposite(trust,embarrass).
opposite(try,do).
opposite(try,want).
opposite(try,need).
opposite(try,extradite).
opposite(try,prefer).
opposite(try,say).
opposite(tuck,wear).
opposite(tumble,rise).
opposite(turn,keep).
opposite(twinkle,mist).
opposite(twist,sprain).
opposite(type,browse).
opposite(type,scrawl).
opposite(uncover,found).
opposite(undercut,bolster).
opposite(undercut,rebut).
opposite(undercut,reflect).
opposite(undercut,reinforce).
opposite(underestimate,overestimate).
opposite(underestimate,overstate).
opposite(underestimate,exaggerate).
opposite(undergo,have).
opposite(undergo,continue).
opposite(undergo,fail).
opposite(undergo,await).
opposite(undergo,finish).
opposite(undergo,refuse).
opposite(underline,outline).
opposite(undermine,endanger).
opposite(undermine,bolster).
opposite(undermine,strengthen).
opposite(undermine,restore).
opposite(undermine,ensure).
opposite(underpay,overpay).
opposite(underpin,undermine).
opposite(underpin,fuel).
opposite(underplay,exaggerate).
opposite(underscore,express).
opposite(underscore,undermine).
opposite(understate,overstate).
opposite(understate,overestimate).
opposite(understate,exaggerate).
opposite(undervalue,overvalue).
opposite(undervalue,value).
opposite(unearth,found).
opposite(unfold,unravel).
opposite(unify,abolish).
opposite(uninstall,overwrite).
opposite(unleash,bring).
opposite(unlock,lock).
opposite(unnerve,excite).
opposite(unravel,unfold).
opposite(unwrap,wrap).
opposite(unzip,don).
opposite(upgrade,downgrade).
opposite(uphold,overturn).
opposite(uphold,invalidate).
opposite(uphold,overrule).
opposite(uphold,reinstate).
opposite(uphold,reject).
opposite(uphold,reverse).
opposite(uphold,reconsider).
opposite(uphold,void).
opposite(uphold,nullify).
opposite(uphold,revoke).
opposite(uphold,challenge).
opposite(uphold,annul).
opposite(uphold,disregard).
opposite(uproot,damage).
opposite(urge,warn).
opposite(urge,praise).
opposite(urge,propose).
opposite(urge,stress).
opposite(urge,condemn).
opposite(urge,accuse).
opposite(vacate,occupy).
opposite(vacate,uphold).
opposite(vacate,affirm).
opposite(validate,invalidate).
opposite(validate,contradict).
opposite(validate,disprove).
opposite(validate,void).
opposite(validate,overturn).
opposite(validate,annul).
opposite(validate,nullify).
opposite(value,undervalue).
opposite(vandalize,torch).
opposite(vanquish,annihilate).
opposite(veto,endorse).
opposite(veto,support).
opposite(veto,approve).
opposite(veto,rescind).
opposite(veto,sign).
opposite(veto,accept).
opposite(vindicate,disprove).
opposite(violate,enforce).
opposite(violate,infringe).
opposite(violate,obey).
opposite(violate,fulfill).
opposite(violate,waive).
opposite(voice,harbor).
opposite(void,uphold).
opposite(void,terminate).
opposite(void,revoke).
opposite(void,validate).
opposite(void,enjoin).
opposite(vow,continue).
opposite(vow,seek).
opposite(voyage,journey).
opposite(wait,get).
opposite(wait,cry).
opposite(waive,impose).
opposite(waive,rescind).
opposite(waive,enforce).
opposite(waive,violate).
opposite(waive,suspend).
opposite(waive,relax).
opposite(waive,invoke).
opposite(waive,extend).
opposite(waive,grant).
opposite(walk,retire).
opposite(walk,pitch).
opposite(walk,hit).
opposite(walk,throw).
opposite(walk,fan).
opposite(walk,whiff).
opposite(want,favor).
opposite(want,know).
opposite(warm,chill).
opposite(warm,cool).
opposite(warn,urge).
opposite(warn,tell).
opposite(warn,condemn).
opposite(warn,praise).
opposite(warn,meet).
opposite(wash,inundate).
opposite(wash,bury).
opposite(wash,dump).
opposite(watch,play).
opposite(watch,do).
opposite(watch,hate).
opposite(wave,throw).
opposite(wave,burn).
opposite(weaken,bolster).
opposite(weaken,strengthen).
opposite(weaken,boost).
opposite(weaken,stabilize).
opposite(weaken,reinforce).
opposite(weaken,heighten).
opposite(weaken,toughen).
opposite(wear,pull).
opposite(weave,wrap).
opposite(wed,marry).
opposite(weigh,eat).
opposite(welcome,reject).
opposite(welcome,condemn).
opposite(welcome,postpone).
opposite(welcome,criticize).
opposite(wheel,tire).
opposite(whet,dull).
opposite(whiff,walk).
opposite(whip,slam).
opposite(whirl,hover).
opposite(whisper,yell).
opposite(white,yellow).
opposite(white,blue).
opposite(widen,narrow).
opposite(widen,shrink).
opposite(widen,restrict).
opposite(wield,grab).
opposite(win,clinch).
opposite(win,lose).
opposite(wish,praise).
opposite(withdraw,reject).
opposite(withdraw,submit).
opposite(withdraw,renew).
opposite(withdraw,withhold).
opposite(withdraw,refuse).
opposite(withdraw,grant).
opposite(withdraw,issue).
opposite(withdraw,deny).
opposite(withhold,disclose).
opposite(withhold,release).
opposite(withhold,grant).
opposite(withhold,withdraw).
opposite(withhold,delay).
opposite(withhold,issue).
opposite(withhold,refuse).
opposite(withhold,revoke).
opposite(withhold,provide).
opposite(withhold,approve).
opposite(withstand,absorb).
opposite(worry,caution).
opposite(worsen,ease).
opposite(worsen,lessen).
opposite(worsen,precipitate).
opposite(worsen,solve).
opposite(worsen,diminish).
opposite(worship,hate).
opposite(wrap,unwrap).
opposite(wrap,weave).
opposite(write,call).
opposite(yell,mutter).
opposite(yell,whisper).
opposite(yell,laugh).
opposite(yell,hear).
opposite(yell,remember).
opposite(yellow,white).


